public enum RequestType {
    GET_QUIZ, SAVE_QUIZ, REMOVE_QUIZ, GET_QUIZ_ATTEMPT, SAVE_QUIZ_ATTEMPT, DELETE_COURSE,
        LOG_IN, TEACHER_SIGN_UP, STUDENT_SIGN_UP, LIST_STUDENTS, LIST_COURSES, CHECK_ACCOUNT_EXISTS
}
